[tool.poetry]
name = "project-ai-gemini"
version = "0.1.0"
description = ""
authors = ["prasannaboga <prasannaboga@gmail.com>"]
readme = "README.md"
packages = [{include = "project_ai_gemini"}]

[tool.poetry.dependencies]
python = "3.12.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
